### ISSUE TITLE
Move link to System > Tools menu

### ISSUE THREAD

**Issue by clockworkgeek** [astorm/PulsestormModuleList#5]
...because, y'know, it's a tool.  I admit it's not _mission critical_ or anything.  Just an idea.

**Comment by astorm** [comment]
Yeah -- it's never been clear where these sort of things belong.  Good suggestion, but I'd be  wary of moving it though after so many years.  Maybe for the Magento 2 version :)

**Comment by clockworkgeek** [comment]
I suppose it's a variation on the [naming things](http://martinfowler.com/bliki/TwoHardThings.html) problem.  Thanks for listening.
