### ISSUE TITLE
compatibility with patch SUPEE-6788

### ISSUE THREAD

**Issue by danielepennati** [astorm/PulsestormModuleList#6]
Hello,
we are using your Magento extension PulsestormModuleList (v. 0.1.0) and I'd like to know if it is compatible with the new SUPEE-6788 Magento Patch that introduce some Backward Compatibility Issue: https://info2.magento.com/rs/318-XBX-392/images/SUPEE-6788-Technical%20Details.pdf

Let me know if it (or the last available version) is compatible.

Thanks
Daniele Pennati

**Comment by astorm** [comment]
Thanks for using the extension!  Unfortunately, we can't answer your question for certain.  The latest version of Module List is definitely works with SUPEE-6788. As for 0.1.0 -- we're uncertain.  There's a good chance it won't, but we couldn't say without seeing the `config.xml` file in use.

Hope that helps!
